<?php

use Illuminate\Database\Seeder;

class ContentPageSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items = [
            
            ['id' => 1, 'title' => 'About us', 'page_text' => 'Sample text', 'excerpt' => 'Sample excerpt', 'featured_image' => '',],
            ['id' => 2, 'title' => 'Terms & Conditions', 'page_text' => '<h5><strong>ntroduction</strong></h5>

<p>Welcome to LiveAuctioneers&#39; Live Auction User Agreement (the &quot;Agreement&quot;). This Agreement contains terms and conditions applicable to your use of the live auction services we host, as well as your participation in live auction events conducted by an Auction House (&quot;Auction House&quot;).</p>

<p>By using the services on any LiveAuctioneers website (i.e., LiveAuctioneers.com and any other related websites where this Agreement appears), you are agreeing to the following terms and conditions, including those available by hyperlink, with LiveAuctioneers , as well as our subsidiaries and affiliates (&quot;LiveAuctioneers&quot;).</p>

<p>Before you may become a member of LiveAuctioneers, you must read and accept all of the terms and conditions in, and referenced by, this Agreement and our Privacy Policy (whether such terms and conditions are contained in the primary document itself or are hyperlinked to related documents). We strongly recommend that, as you read this Agreement, you also access and read all linked information, as well as the listing of&nbsp;<a href="https://www.liveauctioneers.com/terminology">Auction Terminology</a>. Some LiveAuctioneers-branded websites, or sites that we operate, may also be governed by separate user agreements and privacy policies that you should also read.</p>

<p>You acknowledge and agree that we may amend this Agreement at any time, and from time to time, by posting the amended terms on our website. Unless, and only to the extent, expressly stated to the contrary herein, all amended terms and conditions shall automatically be effective on a prospective basis once they are posted on our site. Accordingly, you are encouraged to periodically review our terms of use for any such changes and/or amendments.</p>

<p>&nbsp;</p>

<h5><strong>Live Auction Agreement</strong></h5>

<ol>
	<li>
	<p><strong>Eligibility</strong>. Each Auction House that conducts a live auction will have its own eligibility requirements that must be met in order for you to participate in that auction. You may be required to apply for and obtain approval in order to participate in a specific live auction. Approval to participate in one live auction does not guarantee approval to participate in any other live auction, conducted either by that Auction House, or another Auction House. Each Auction House has sole and absolute discretion to refuse to approve your eligibility for any live auction.</p>
	</li>
	<li>
	<p><strong>Fees</strong>. Each Auction House may charge a buyer&#39;s premium (which is an additional fee that a winning bidder is required to pay above the auction price) as well as shipping, handling, and other fees. These fees are subject to change depending upon the Auction House and the particular item for sale, and are set by the Auction House.</p>
	</li>
	<li>
	<p><strong>LiveAuctioneers is Only a Venue</strong>.</p>

	<p><strong>(a) Services</strong>. We are not an auction house and are not conducting the live auctions. Our service allows you to participate in live auctions conducted by the Auction House. We are solely a passive conduit to facilitate communication between you and the Auction House. We reserve the right in our sole and absolute discretion to change some or all of our services at any time.</p>

	<p><strong>(b) Control</strong>. We have no control over the quality, safety, or legality of the items advertised, the truth or accuracy of the listings, or the ability of the Auction House to sell and the ability of buyers to buy items. We also do not ensure or guarantee that a buyer or seller will actually complete a transaction.</p>

	<p><strong>(c) Compliance with Laws</strong>. You acknowledge and agree that the use, purchase, distribution, promotion, advertising, and sale of certain products are subject to federal state, and local regulations, including, but not limited to, firearms, Indian artifacts, recalled products, children&#39;s products, alcoholic beverages, coins and currency. You further acknowledge and agree that LiveAuctioneers&#39; role with respect to the sale of products is limited to providing a conduit through which a prospective purchaser is able to participate in an auction. LiveAuctioneers does not review or evaluate the products auctioned, or verify the descriptions given or claims made, by Auction Houses regarding the products. You expressly represent that you shall comply with all applicable federal, state, and local laws, statutes, ordinances, and regulations relating to your use, purchase, and distribution of any products that you bid upon or purchase through LiveAuctioneers (hereinafter, the &quot;Regulations&quot;), including, but not limited to, (i) the Gun Control Act of 1968 and all regulations promulgated by the Bureau of Alcohol, Tobacco, Firearms, and Explosives (collectively, the &quot;Firearms Regulations&quot;), (ii) the Consumer Products Safety Improvement Act of 2008 and all regulations promulgated by the U.S. Consumer Products Safety Commission, and (iii) the Indian Arts &amp; Crafts Act of 1990 and any additional laws and regulations applicable to the sale of Indian arts and crafts. You shall at all times defend, indemnify and hold LiveAuctioneers, its shareholders, members, partners, officers, directors, employees, agents, parent, subsidiaries, affiliates, joint venturers, and successors and assigns, harmless from, and against, any and all causes of action, suits, claims, demands, judgments, liabilities, losses, damages, awards, penalties, fines, costs and expenses (including, but not limited to, reasonable attorney&#39;s fees) of any nature or kind, arising under or resulting from: (i) your use, purchase, or distribution of any products in violation of any Regulations; (ii) your use of LiveAuctioneers in connection with the purchase of any products subject to any Regulations; and (iii) your alleged or actual violation or breach of any Regulations.</p>

	<p><strong>(d) Release</strong>. Since we are not involved in the actual transactions between buyers and Auction Houses, in the event that you have a dispute with an Auction House, you hereby release LiveAuctioneers (and our shareholders, members, partners, officers, directors, employees, agents, parent, subsidiaries, affiliates, joint venturers, and successors and assigns) from causes of action, suits, claims, demands, judgments, and damages (actual and consequential) of every kind and nature, known and unknown, suspected and unsuspected, disclosed and undisclosed, arising out of, or in any way connected with, such disputes. If you are a California resident, you waive California Civil Code &Acirc;&sect; 1542, as amended from time to time, and any similar statutes, to the extent that such statute(s) prohibits a general release from extending to claims that a creditor does not know or suspect to exist in his/her favor at the time of executing the release, which if known by the creditor, would materially affect his/her settlement with the debtor.</p>
	</li>
	<li>
	<p><strong>Auction Houses</strong>. The Auction House will list available items on which you may bid. Auction dates and times, as well as the number, character, and order and schedule of the items to be auctioned, are set by the Auction House and are subject to change without notice. Individual lots and items may be modified or changed at any time. Some lots and items that are made available on the auction floor will not be included in the online live auction services. We do not control the information that is provided by the Auction House, which is made available through our system. We also do not guarantee that the Auction House maintains proper auctioneers&#39; licenses or complies with all applicable laws, rules, and regulations.</p>
	</li>
	<li>
	<p><strong>Bidding, Buying and Conditions of Sale</strong>. The terms and conditions for participation in each auction, including how bids are accepted, rules governing absentee bids, bid increments, bid retraction and cancellation, the conditions the buyer must meet to purchase an item, as well as the specific conditions of sale (such as warranties, shipping costs, insurance, and the like) may change for each auction at the sole discretion of the Auction House. The Auction House is required to post its terms and conditions and to maintain such terms throughout the auction period. You agree to be bound by those bidding terms and conditions of sale by agreeing to this Agreement. This Agreement, in addition to those Auction House terms and conditions, governs your bidding activity, as well as your participation in each auction. The Auction House acts as an auctioneer and makes the sole, final determination with respect to bidding on the item, the sale of the item, and the resolution of any disputes. All matters relating to a refund or return of won items are also determined by the outlined terms and conditions of the Auction House.</p>
	</li>
	<li>
	<p><strong>Video and Audio</strong>. Any audio or video aspects of a live auction event are for entertainment purposes only.</p>
	</li>
	<li>
	<p><strong>Use of Images</strong>. LiveAuctioneers has the right to use, on its website and in advertising and promotional materials, images (including photographic images) of items being sold or that have been sold on its website, including images of items which have been purchased through the site.</p>
	</li>
	<li>
	<p><strong>Using LiveAuctioneers</strong>. While using LiveAuctioneers, you shall not: (a) violate any laws, rules, regulations or third party rights; (b) use our sites or services if you are not able to form legally binding contracts, are under the age of 18, or are temporarily or indefinitely suspended from our sites; (c) fail to deliver payment on any item that you purchased through our sites; (d) manipulate the price of any item or interfere with other user&#39;s listings; (e) post false, inaccurate, misleading, defamatory, or libelous content (including personal information); (f) distribute or post spam, chain letters, or pyramid schemes; (g) distribute viruses or any other technologies that may harm LiveAuctioneers, our sites, or the interests or property of LiveAuctioneers&#39; users; (h) copy, modify, or distribute content from our sites and/or violate LiveAuctioneers&#39;s copyrights and trademarks; or (i) harvest or otherwise collect information about users, including, without limitation, email addresses, without their consent. Nor shall you encourage or assist any third party to engage in any of the prohibited conduct set forth above. Any violation of this provision shall constitute a material breach of this Agreement and, under such circumstances, we will have the right, in our sole and absolute discretion, to prohibit your access to our sites and to suspend or terminate your right to use our services.</p>
	</li>
	<li>
	<p><strong>Abusing LiveAuctioneers</strong>. (a) LiveAuctioneers will work to keep our sites and services working properly and safely. Please report problems, offensive content, and any policy violations to us. (b)Without limiting our remedies, it is understood that we may limit, suspend, or terminate our services and user accounts, prohibit access to our sites, delay or remove hosted content, and take technical and legal steps to keep users off our sites if we believe that they are misusing, abusing, or interfering with the provision of our services, engaging in unlawful conduct, or acting inconsistently with the letter or spirit of our policies. We also reserve the right to cancel unconfirmed accounts or accounts that have been inactive for a long time.</p>
	</li>
	<li>
	<p><strong>Access and Interference</strong>. The sites contains robot exclusion headers. Much of the information on the sites is updated on a real-time basis and is proprietary or is licensed to LiveAuctioneers by our users or third parties. You agree that you will not use any robot, spider, scraper or other automated means to access the sites for any purpose without our express written permission. Additionally, you agree that you will not: (a) take any action that imposes or may impose (in our sole discretion) an unreasonable or disproportionately large load on our infrastructure; (b) copy, reproduce, modify, create derivative works from, distribute, or publicly display any content (except for your information) from the sites without the prior, express written consent of LiveAuctioneers and the appropriate third party, as applicable; (c) interfere or attempt to interfere with the proper working of our sites or any activities conducted on the sites; or (d) bypass our robot exclusion headers or other measures we may use to prevent or restrict access to the sites.</p>
	</li>
	<li>
	<p><strong>Privacy</strong>. Any information you provide to us, and your use of information available on our websites, is governed by our&nbsp;<a href="https://www.liveauctioneers.com/privacy">Privacy Policy</a>. Any information you provide to the Auction House or other third parties is governed by their respective privacy policies. We do not sell or rent your personal information to third parties for their marketing purposes without your express consent. We use your information only as described in the LiveAuctioneers Privacy Policy. We consider protection of our users&#39; privacy as a high priority. We store and process your information on computers located in the United States that are protected by physical as well as technological security devices. You can access and modify the information you provide. We use third parties to verify and certify our privacy security methods. For a complete description of how we use and protect your personal information, please review the LiveAuctioneers Privacy Policy. If you object to your information being transferred or used in this way, please do not use our services.</p>
	</li>
	<li>
	<p><strong>Intellectual Property/Restrictions on Use</strong>. We reserve all rights with respect to the design and content of our websites. In particular, you may not misappropriate the design or content of our sites and you may not alter or deface such design or content in any way. Nothing on our websites grants any license with respect to such design or content. All trademarks, service marks, trade names, logos, graphics, articles and other materials on our sites are protected by United States and foreign copyright, trademark and other applicable laws. In particular, all trademarks, service marks, trade names and logos displayed on our sites are proprietary to LiveAuctioneers , its affiliates, or third-party owners and our websites grant no license thereto. You acknowledge that you have read, and will at all times comply with, LiveAuctioneers&#39;<a href="https://www.liveauctioneers.com/intellectualproperty">Intellectual Property</a>&nbsp;statement.</p>
	</li>
	<li>
	<p><strong>Indemnity</strong>. You will defend, indemnify and hold LiveAuctioneers, its shareholders, members, partners, officers, directors, employees, agents, parent, subsidiaries, affiliates, joint venturers, and successors and assigns, harmless from, and against, any and all causes of action, suits, claims, demands, judgments, liabilities, losses, damages, awards, penalties, fines, costs and expenses (including, but not limited to, reasonable attorney&#39;s fees), sought by any third party and which results from, or arises out of, your breach of this Agreement, your unlawful actions or conduct, or your violation of the rights of any third party.</p>
	</li>
	<li>
	<p><strong>No Agency</strong>. No agency, partnership, joint venture, employee-employer or franchiser-franchisee relationship is intended or created by this Agreement.</p>
	</li>
	<li>
	<p><strong>No Warranty</strong>. WE AND OUR SUPPLIERS PROVIDE OUR WEB SITE AND SERVICES &quot;AS IS&quot; AND WITHOUT ANY WARRANTY OR CONDITION, EXPRESS, IMPLIED OR STATUTORY. WITHOUT LIMITING THE FOREGOING, WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED OR ERROR FREE, OR THAT BIDS WILL BE RECEIVED BY THE AUCTION HOUSE OR INFORMATION REGARDING CURRENT PRICE WILL BE TRANSMITTED IN A TIMELY FASHION. NOR DO WE GUARANTEE THE PERFORMANCE OF ANY OBLIGATIONS BY AN AUCTION HOUSE. WE AND OUR SUPPLIERS SPECIFICALLY DISCLAIM ANY IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. Some states&#39; laws may not allow a disclaimer of implied warranties in certain circumstances, in which case the foregoing disclaimer may not apply to you. This warranty gives you specific legal rights and you also may have other legal rights which vary from state to state.</p>
	</li>
	<li>
	<p><strong>Liability Limit</strong>. IN NO EVENT SHALL WE OR OUR SUPPLIERS BE LIABLE FOR LOST PROFITS OR ANY SPECIAL, INDIRECT, INCIDENTAL OR CONSEQUENTIAL DAMAGES ARISING OUT OF, OR IN CONNECTION WITH, OUR SITES, OUR SERVICES, THE FAILURE OF ANY BID OR PRICING INFORMATION TO BE TRANSMITTED OR RECEIVED BY YOU OR THE AUCTION HOUSE IN A TIMELY MANNER, THE INTERRUPTION OF ANY DATA TRANSMISSION, AUDIO OR VIDEO BROADCAST, OR THIS AGREEMENT (REGARDLESS OF THE FORM OF ACTION, WHETHER IN CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY OR OTHERWISE). OUR LIABILITY, AND THE LIABILITY OF OUR SUPPLIERS, TO YOU OR ANY THIRD PARTIES IN ANY CIRCUMSTANCE IS LIMITED TO THE GREATER OF (A) THE AMOUNT OF FEES YOU PAY TO US IN THE 12 MONTHS PRIOR TO THE ACTION GIVING RISE TO LIABILITY, AND (B) $100.00. Some states&#39; laws may not allow a limitation of liability in certain circumstances, in which case the foregoing limitation may not apply to you.</p>
	</li>
	<li>
	<p><strong>Notices</strong>. Any notice, demand, request or other communication which you may desire or be required to give to LiveAuctioneers hereunder shall be in writing and shall be given by certified mail, return receipt requested (with postage prepaid), or by Federal Express or other similar overnight delivery service (with fees prepaid), to LiveAuctioneers , 220 12th Avenue, 2nd Floor, New York, NY 10001, or at any other address that we may designate in writing in the future. Any notice, demand, request or other communication which we may desire or be required to give to you hereunder shall be in writing and shall be given by email to the email address you provided to LiveAuctioneers during the registration process, or by certified mail, return receipt requested (with postage prepaid), or by Federal Express or other similar overnight delivery service (with fees prepaid), to you at the address you provided to LiveAuctioneers during the registration process. All notices given by e-mail shall be deemed given as of 5:00 P.M. eastern standard time on the business day following the day of transmission. All notices given by mail shall be deemed to have been given three (3) business days after mailing and all notices delivered by overnight delivery service shall be deemed given when delivered.</p>
	</li>
	<li>
	<p><strong>Force Majeure</strong>. No party shall be liable for any failure or delay in performing any obligation under this Agreement that is due to a Force Majeure event, such as Acts of God (including fire, flood, earthquake, storm, hurricane or other natural disaster), war, invasion, act of foreign enemies, hostilities (regardless of whether war is declared), civil war, rebellion, revolution, insurrection, military or usurped power or confiscation, terrorist activities, nationalization, government sanction, blockage, embargo, labor dispute, strike, lockout or interruption or failure of electricity or telephone service). If a Force Majeure event occurs, the affected party will notify the other party and make commercially reasonable efforts to mitigate the adverse effects of the Force Majeure event on the performance of this Agreement. However, this provision does not excuse your obligation to pay for services actually received.</p>
	</li>
	<li>
	<p><strong>Arbitration</strong>. If a dispute, controversy, claim or cause of action arises out of, or in connection with, this Agreement or any breach or alleged breach thereof (the &quot;Dispute&quot;), and if the Dispute cannot be settled through direct discussions, we mutually agree to endeavor first to settle the Dispute by mediation administered by the American Arbitration Association under its Commercial Mediation Procedures then in effect (or under any other form of mediation mutually acceptable to the parties involved) before resorting to arbitration. Any unresolved controversy or claim relating to the Dispute shall be settled by arbitration administered by the American Arbitration Association in accordance with its Commercial Arbitration Rules then in effect (or under any other form of arbitration mutually acceptable to the parties involved), and judgment on the award rendered by the arbitrator may be entered in any court having jurisdiction thereof. If all parties to the Dispute agree, a mediator involved in the parties&#39; mediation may be asked to serve as the arbitrator. The mediation and arbitration, if any, shall take place in the City, State, and County of New York (unless another location is mutually agreed to by the parties involved). Any award rendered shall be final and conclusive upon the parties. The costs and expenses of the mediation and arbitration shall be borne equally by the parties, provided, however, that the arbitrator shall award to the prevailing party, if any, the reasonable costs and attorneys&#39; fees incurred by the prevailing party in connection with the mediation and arbitration. If the arbitrator determines that a party was the prevailing party on some but not all of the claims and counterclaims, the arbitrator may award the prevailing party an appropriate percentage of the reasonable costs and attorneys&#39; fees incurred by the prevailing party in connection with the mediation and arbitration. In the event this mediation/arbitration provision is found to be completely unenforceable or inapplicable for any reason, then any dispute, controversy, claim or cause of action arising out of, or in connection with, this Agreement or any breach or alleged breach thereof, shall be brought in the state or federal courts in the City, State, and County of New York, and you irrevocably consent and submit to the jurisdiction of such courts for the purpose of litigating any such action and waive trial by jury. The prevailing party in such action shall be entitled to recover its reasonable costs and attorneys&#39; fees incurred in connection therewith, and if it is determined that a party was the prevailing party on some but not all of the claims and counterclaims, such party may be awarded an appropriate percentage of the reasonable costs and attorneys&#39; fees it incurred in connection therewith.</p>
	</li>
	<li>
	<p><strong>General</strong>. (a) This Agreement constitutes and sets forth the entire agreement and understanding of the parties pertaining to the subject matter hereof, and supersedes all prior or contemporaneous written or oral agreements, understandings, undertakings, negotiations, promises, discussions, warranties or covenants that are not specifically contained herein; (b) The headings, sections, or titles of the various paragraphs of this Agreement are inserted merely for the purpose of convenience and do not expressly or by implication or intention, limit, define, extend or affect the meaning or interpretation of this Agreement or the specific terms or text of the section so designated. All personal pronouns used in this Agreement shall include the other genders, whether used in the masculine, feminine or neuter gender, and the singular shall include the plural and vice versa, whenever, and as often as may be, appropriate; (c) This Agreement shall be governed in all respects, whether as to validity, construction, interpretation, capacity, performance or otherwise, by the laws of the State of New York, without regard to principles of conflicts of laws; (d) If any provision of this Agreement is found invalid or unenforceable by a court of competent jurisdiction, then such provision shall be deemed stricken herefrom and the remainder of this Agreement shall remain at all times in full force and effect. Such invalid or enforceable provision shall, to the extent legally permitted, be replaced by a valid and enforceable provision that comes closest to the parties&#39; intent underlying the invalid or unenforceable provision; (e) It is understood that any accrued but unpaid financial obligations, and any other terms related to such financial obligations, shall survive the expiration or termination of this Agreement; (f) No waiver of any breach, privilege or provision of this Agreement will be construed as a waiver of any rights or remedies arising from any other or future breach, privilege or provision; (g) We may, in our sole discretion, assign or otherwise transfer this Agreement to a third party.</p>
	</li>
	<li>
	<p><strong>Future Terms</strong>. LiveAuctioneers may amend, modify, add or remove any of these terms and conditions at any time, and from time to time. If we do so, we will post such changes on this page. IF ANY FUTURE CHANGES TO THESE TERMS AND CONDITIONS ARE UNACCEPTABLE TO YOU, YOU SHOULD DISCONTINUE USING THE SERVICES. YOUR CONTINUED USE OF THE SERVICES NOW, OR FOLLOWING THE POSTING OF NOTICE OF ANY SUCH CHANGES, WILL INDICATE YOUR ACCEPTANCE OF THESE TERMS AND CONDITIONS, AND OF ANY SUCH CHANGES.</p>
	</li>
</ol>
', 'excerpt' => null, 'featured_image' => null,],
            ['id' => 3, 'title' => 'Privacy Policy', 'page_text' => '<h4>Our Commitment To Privacy</h4>

<p>LiveAuctioneers is committed to maintaining user privacy on the Live Auctioneers&#39; website at www.liveauctioneers.com (the &quot;Site&quot;). Our Private Policy governs use of personal information provided to us through the use of the Site. By accessing the Site you agree to be bound by the terms and conditions of this Privacy Policy. If you do not agree to its terms and conditions, you should not use or access our Site. By accepting the Privacy Policy, you expressly consent to our use and disclosure of your personal information in accordance with the policy. The Privacy Policy is incorporated into and subject to the terms of any agreement you sign with LiveAuctioneers and becomes applicable upon our acceptance of you as a registered user. If you have any additional questions about our Privacy Policy, please feel free to contact us at&nbsp;<a href="mailto:info@liveauctioneers.com">info@liveauctioneers.com</a></p>

<h4>Use of Our Site by Children</h4>

<p>Children (persons under the age of 18) are not eligible to use the Site unsupervised and we ask that children do not submit any personal information. If you are under the age of 18, you may only use this Site in conjunction with and under the supervision of parents or guardians.</p>

<h4>Information We Collect</h4>

<p>If you choose to use our services, we may require that you provide contact and identity information, billing information, shipping information, as well as other personal information as indicated on the forms throughout the Site. Where possible, we indicate fields that are required and those that are optional. You are not required to provide information if you choose not to use a particular service or feature. Please be advised that we may use your financial information, including credit card information, to verify the accuracy of your name, address, and other personal information, as well as to bill you for use of our services. Certain information is automatically tracked based on your activity on the Site. We use this information for internal research on user demographics, interests, and behavior so as to better understand, protect and serve you and our community. This information may include the URL that you previously visited (whether this URL is on the Site or not), the subsequent URL you visited (whether this URL is on the Site or not), your computer browser information, and your IP address. We may collect browser and Internet-related information through access to our Site, via cookies, and/or web beacons. If you send us personal correspondence, such as emails or letters, or if other users or third parties send us correspondence regarding your activities or postings on the Site, we may accumulate such information into a file specific to you.</p>

<h4>Our Use of Your Information</h4>

<p>We use your personal information to facilitate the services you personally request. Your contact information and bidding history will be passed onto the Auction Companies during the auction sign-up process for them to make a decision whether you are able to bid in their auction. We also use your personal file information and activity information to: resolve disputes; troubleshoot problems; collect fees owed; measure consumer interest in our products and services; inform you about online and offline offers, products, services, and updates; customize your experience; detect and protect us against error, fraud and other criminal activity; enforce applicable agreements; and as otherwise described to you at the time of collection. Providing us with your personal information indicates that you agree to our use of any personal information to improve our marketing and promotional efforts, to analyze Site usage, improve our content and product offerings, and customize the Site&#39;s content, layout, and services. In turn, we are able to improve the Site and better tailor it to meet your needs, providing you with a smooth, efficient, safe and customized experience. We also reserve the right to use your information to make contact and deliver information that, in some cases, is targeted to your interests. Examples include targeted banner advertisements, administrative notices, product offerings, and communication relevant to your use of the Site. By accepting this Privacy Policy, you expressly agree to receive this information, however, you may contact us at&nbsp;<a href="mailto:info@liveauctioneers.com">info@liveauctioneers.com</a>&nbsp;should you wish to cease receipt of such information.</p>

<h4>Our Disclosure of Your Information</h4>

<p>While we use your information to provide you with access to our site and services, we also use your information to contact you regarding our services, offerings, or information you may have requested. We use your information to improve and personalize our Site so as to make it easier, safer, and quicker to use. Due to the existing regulatory environment, we cannot ensure that all of your private communication and other personal information will never be disclosed in ways not otherwise described in this Privacy Policy. By way of example (without limiting the foregoing), we may be forced under certain circumstances to disclose personal information to the government or third parties, unaffiliated parties may unlawfully intercept or access transmissions or private communication, or users may abuse or misuse your personal information collected from the Site. Therefore, although we use industry standard practices to protect your privacy, we do not promise, and you should not expect, that your personal information or private communication will always remain completely private.</p>

<h4>Security</h4>

<p>We store your information in the United States. In order to prevent unauthorized access, maintain data accuracy, and ensure appropriate use of information, we use industry-leading technical and administrative practices and procedures that safeguard and secure your information.</p>

<h4>Notice</h4>

<p>We may occasionally choose to amend this Privacy Policy to better reflect our use and protection of your information. In the event of revision, all terms shall become effective within 15 days of initial posting to the Site.</p>
', 'excerpt' => null, 'featured_image' => null,],
            ['id' => 4, 'title' => 'Copyright & Usage', 'page_text' => '<p>All content, images, and intellectual property on this site protected by digital watermark technology. Digital copying of images strictly prohibited; violators will be pursued and prosecuted to the full extent of the law including the Digital Millennium Copyright Act.</p>

<p>Unauthorized use including account sharing of Invaluable will result in permanent account cancellation.</p>

<p>Copyright &copy; 1986-2018 Invaluable, LLC and participating auction houses. All Rights Reserved.</p>
', 'excerpt' => null, 'featured_image' => null,],

        ];

        foreach ($items as $item) {
            \App\ContentPage::create($item);
        }
    }
}
