<?php

use Illuminate\Database\Seeder;

class CountrySeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items = [
            
            ['id' => 1, 'shortcode' => 'AF', 'title' => 'Afghanistan', 'created_by_id' => null,],
            ['id' => 2, 'shortcode' => 'AL', 'title' => 'Albania', 'created_by_id' => null,],
            ['id' => 3, 'shortcode' => 'DZ', 'title' => 'Algeria', 'created_by_id' => null,],
            ['id' => 4, 'shortcode' => 'AS', 'title' => 'American Samoa', 'created_by_id' => null,],
            ['id' => 5, 'shortcode' => 'AD', 'title' => 'Andorra', 'created_by_id' => null,],
            ['id' => 6, 'shortcode' => 'AO', 'title' => 'Angola', 'created_by_id' => null,],
            ['id' => 7, 'shortcode' => 'AI', 'title' => 'Anguilla', 'created_by_id' => null,],
            ['id' => 8, 'shortcode' => 'AQ', 'title' => 'Antarctica', 'created_by_id' => null,],
            ['id' => 9, 'shortcode' => 'AG', 'title' => 'Antigua and Barbuda', 'created_by_id' => null,],
            ['id' => 10, 'shortcode' => 'AR', 'title' => 'Argentina', 'created_by_id' => null,],
            ['id' => 11, 'shortcode' => 'AM', 'title' => 'Armenia', 'created_by_id' => null,],
            ['id' => 12, 'shortcode' => 'AW', 'title' => 'Aruba', 'created_by_id' => null,],
            ['id' => 13, 'shortcode' => 'AU', 'title' => 'Australia', 'created_by_id' => null,],
            ['id' => 14, 'shortcode' => 'AT', 'title' => 'Austria', 'created_by_id' => null,],
            ['id' => 15, 'shortcode' => 'AZ', 'title' => 'Azerbaijan', 'created_by_id' => null,],
            ['id' => 16, 'shortcode' => 'BS', 'title' => 'Bahamas', 'created_by_id' => null,],
            ['id' => 17, 'shortcode' => 'BH', 'title' => 'Bahrain', 'created_by_id' => null,],
            ['id' => 18, 'shortcode' => 'BD', 'title' => 'Bangladesh', 'created_by_id' => null,],
            ['id' => 19, 'shortcode' => 'BB', 'title' => 'Barbados', 'created_by_id' => null,],
            ['id' => 20, 'shortcode' => 'BY', 'title' => 'Belarus', 'created_by_id' => null,],
            ['id' => 21, 'shortcode' => 'BE', 'title' => 'Belgium', 'created_by_id' => null,],
            ['id' => 22, 'shortcode' => 'BZ', 'title' => 'Belize', 'created_by_id' => null,],
            ['id' => 23, 'shortcode' => 'BJ', 'title' => 'Benin', 'created_by_id' => null,],
            ['id' => 24, 'shortcode' => 'BM', 'title' => 'Bermuda', 'created_by_id' => null,],
            ['id' => 25, 'shortcode' => 'BT', 'title' => 'Bhutan', 'created_by_id' => null,],
            ['id' => 26, 'shortcode' => 'BO', 'title' => 'Bolivia', 'created_by_id' => null,],
            ['id' => 27, 'shortcode' => 'BA', 'title' => 'Bosnia and Herzegovina', 'created_by_id' => null,],
            ['id' => 28, 'shortcode' => 'BW', 'title' => 'Botswana', 'created_by_id' => null,],
            ['id' => 29, 'shortcode' => 'BV', 'title' => 'Bouvet Island', 'created_by_id' => null,],
            ['id' => 30, 'shortcode' => 'BR', 'title' => 'Brazil', 'created_by_id' => null,],
            ['id' => 31, 'shortcode' => 'BQ', 'title' => 'British Antarctic Territory', 'created_by_id' => null,],
            ['id' => 32, 'shortcode' => 'IO', 'title' => 'British Indian Ocean Territory', 'created_by_id' => null,],
            ['id' => 33, 'shortcode' => 'VG', 'title' => 'British Virgin Islands', 'created_by_id' => null,],
            ['id' => 34, 'shortcode' => 'BN', 'title' => 'Brunei', 'created_by_id' => null,],
            ['id' => 35, 'shortcode' => 'BG', 'title' => 'Bulgaria', 'created_by_id' => null,],
            ['id' => 36, 'shortcode' => 'BF', 'title' => 'Burkina Faso', 'created_by_id' => null,],
            ['id' => 37, 'shortcode' => 'BI', 'title' => 'Burundi', 'created_by_id' => null,],
            ['id' => 38, 'shortcode' => 'KH', 'title' => 'Cambodia', 'created_by_id' => null,],
            ['id' => 39, 'shortcode' => 'CM', 'title' => 'Cameroon', 'created_by_id' => null,],
            ['id' => 40, 'shortcode' => 'CA', 'title' => 'Canada', 'created_by_id' => null,],
            ['id' => 41, 'shortcode' => 'CT', 'title' => 'Canton and Enderbury Islands', 'created_by_id' => null,],
            ['id' => 42, 'shortcode' => 'CV', 'title' => 'Cape Verde', 'created_by_id' => null,],
            ['id' => 43, 'shortcode' => 'KY', 'title' => 'Cayman Islands', 'created_by_id' => null,],
            ['id' => 44, 'shortcode' => 'CF', 'title' => 'Central African Republic', 'created_by_id' => null,],
            ['id' => 45, 'shortcode' => 'TD', 'title' => 'Chad', 'created_by_id' => null,],
            ['id' => 46, 'shortcode' => 'CL', 'title' => 'Chile', 'created_by_id' => null,],
            ['id' => 47, 'shortcode' => 'CN', 'title' => 'China', 'created_by_id' => null,],
            ['id' => 48, 'shortcode' => 'CX', 'title' => 'Christmas Island', 'created_by_id' => null,],
            ['id' => 49, 'shortcode' => 'CC', 'title' => 'Cocos [Keeling] Islands', 'created_by_id' => null,],
            ['id' => 50, 'shortcode' => 'CO', 'title' => 'Colombia', 'created_by_id' => null,],
            ['id' => 51, 'shortcode' => 'KM', 'title' => 'Comoros', 'created_by_id' => null,],
            ['id' => 52, 'shortcode' => 'CG', 'title' => 'Congo - Brazzaville', 'created_by_id' => null,],
            ['id' => 53, 'shortcode' => 'CD', 'title' => 'Congo - Kinshasa', 'created_by_id' => null,],
            ['id' => 54, 'shortcode' => 'CK', 'title' => 'Cook Islands', 'created_by_id' => null,],
            ['id' => 55, 'shortcode' => 'CR', 'title' => 'Costa Rica', 'created_by_id' => null,],
            ['id' => 56, 'shortcode' => 'HR', 'title' => 'Croatia', 'created_by_id' => null,],
            ['id' => 57, 'shortcode' => 'CU', 'title' => 'Cuba', 'created_by_id' => null,],
            ['id' => 58, 'shortcode' => 'CY', 'title' => 'Cyprus', 'created_by_id' => null,],
            ['id' => 59, 'shortcode' => 'CZ', 'title' => 'Czech Republic', 'created_by_id' => null,],
            ['id' => 60, 'shortcode' => 'CI', 'title' => 'Côte d’Ivoire', 'created_by_id' => null,],
            ['id' => 61, 'shortcode' => 'DK', 'title' => 'Denmark', 'created_by_id' => null,],
            ['id' => 62, 'shortcode' => 'DJ', 'title' => 'Djibouti', 'created_by_id' => null,],
            ['id' => 63, 'shortcode' => 'DM', 'title' => 'Dominica', 'created_by_id' => null,],
            ['id' => 64, 'shortcode' => 'DO', 'title' => 'Dominican Republic', 'created_by_id' => null,],
            ['id' => 65, 'shortcode' => 'NQ', 'title' => 'Dronning Maud Land', 'created_by_id' => null,],
            ['id' => 66, 'shortcode' => 'DD', 'title' => 'East Germany', 'created_by_id' => null,],
            ['id' => 67, 'shortcode' => 'EC', 'title' => 'Ecuador', 'created_by_id' => null,],
            ['id' => 68, 'shortcode' => 'EG', 'title' => 'Egypt', 'created_by_id' => null,],
            ['id' => 69, 'shortcode' => 'SV', 'title' => 'El Salvador', 'created_by_id' => null,],
            ['id' => 70, 'shortcode' => 'GQ', 'title' => 'Equatorial Guinea', 'created_by_id' => null,],
            ['id' => 71, 'shortcode' => 'ER', 'title' => 'Eritrea', 'created_by_id' => null,],
            ['id' => 72, 'shortcode' => 'EE', 'title' => 'Estonia', 'created_by_id' => null,],
            ['id' => 73, 'shortcode' => 'ET', 'title' => 'Ethiopia', 'created_by_id' => null,],
            ['id' => 74, 'shortcode' => 'FK', 'title' => 'Falkland Islands', 'created_by_id' => null,],
            ['id' => 75, 'shortcode' => 'FO', 'title' => 'Faroe Islands', 'created_by_id' => null,],
            ['id' => 76, 'shortcode' => 'FJ', 'title' => 'Fiji', 'created_by_id' => null,],
            ['id' => 77, 'shortcode' => 'FI', 'title' => 'Finland', 'created_by_id' => null,],
            ['id' => 78, 'shortcode' => 'FR', 'title' => 'France', 'created_by_id' => null,],
            ['id' => 79, 'shortcode' => 'GF', 'title' => 'French Guiana', 'created_by_id' => null,],
            ['id' => 80, 'shortcode' => 'PF', 'title' => 'French Polynesia', 'created_by_id' => null,],
            ['id' => 81, 'shortcode' => 'TF', 'title' => 'French Southern Territories', 'created_by_id' => null,],
            ['id' => 82, 'shortcode' => 'FQ', 'title' => 'French Southern and Antarctic Territories', 'created_by_id' => null,],
            ['id' => 83, 'shortcode' => 'GA', 'title' => 'Gabon', 'created_by_id' => null,],
            ['id' => 84, 'shortcode' => 'GM', 'title' => 'Gambia', 'created_by_id' => null,],
            ['id' => 85, 'shortcode' => 'GE', 'title' => 'Georgia', 'created_by_id' => null,],
            ['id' => 86, 'shortcode' => 'DE', 'title' => 'Germany', 'created_by_id' => null,],
            ['id' => 87, 'shortcode' => 'GH', 'title' => 'Ghana', 'created_by_id' => null,],
            ['id' => 88, 'shortcode' => 'GI', 'title' => 'Gibraltar', 'created_by_id' => null,],
            ['id' => 89, 'shortcode' => 'GR', 'title' => 'Greece', 'created_by_id' => null,],
            ['id' => 90, 'shortcode' => 'GL', 'title' => 'Greenland', 'created_by_id' => null,],
            ['id' => 91, 'shortcode' => 'GD', 'title' => 'Grenada', 'created_by_id' => null,],
            ['id' => 92, 'shortcode' => 'GP', 'title' => 'Guadeloupe', 'created_by_id' => null,],
            ['id' => 93, 'shortcode' => 'GU', 'title' => 'Guam', 'created_by_id' => null,],
            ['id' => 94, 'shortcode' => 'GT', 'title' => 'Guatemala', 'created_by_id' => null,],
            ['id' => 95, 'shortcode' => 'GG', 'title' => 'Guernsey', 'created_by_id' => null,],
            ['id' => 96, 'shortcode' => 'GN', 'title' => 'Guinea', 'created_by_id' => null,],
            ['id' => 97, 'shortcode' => 'GW', 'title' => 'Guinea-Bissau', 'created_by_id' => null,],
            ['id' => 98, 'shortcode' => 'GY', 'title' => 'Guyana', 'created_by_id' => null,],
            ['id' => 99, 'shortcode' => 'HT', 'title' => 'Haiti', 'created_by_id' => null,],
            ['id' => 100, 'shortcode' => 'HM', 'title' => 'Heard Island and McDonald Islands', 'created_by_id' => null,],
            ['id' => 101, 'shortcode' => 'HN', 'title' => 'Honduras', 'created_by_id' => null,],
            ['id' => 102, 'shortcode' => 'HK', 'title' => 'Hong Kong SAR China', 'created_by_id' => null,],
            ['id' => 103, 'shortcode' => 'HU', 'title' => 'Hungary', 'created_by_id' => null,],
            ['id' => 104, 'shortcode' => 'IS', 'title' => 'Iceland', 'created_by_id' => null,],
            ['id' => 105, 'shortcode' => 'IN', 'title' => 'India', 'created_by_id' => null,],
            ['id' => 106, 'shortcode' => 'ID', 'title' => 'Indonesia', 'created_by_id' => null,],
            ['id' => 107, 'shortcode' => 'IR', 'title' => 'Iran', 'created_by_id' => null,],
            ['id' => 108, 'shortcode' => 'IQ', 'title' => 'Iraq', 'created_by_id' => null,],
            ['id' => 109, 'shortcode' => 'IE', 'title' => 'Ireland', 'created_by_id' => null,],
            ['id' => 110, 'shortcode' => 'IM', 'title' => 'Isle of Man', 'created_by_id' => null,],
            ['id' => 111, 'shortcode' => 'IL', 'title' => 'Israel', 'created_by_id' => null,],
            ['id' => 112, 'shortcode' => 'IT', 'title' => 'Italy', 'created_by_id' => null,],
            ['id' => 113, 'shortcode' => 'JM', 'title' => 'Jamaica', 'created_by_id' => null,],
            ['id' => 114, 'shortcode' => 'JP', 'title' => 'Japan', 'created_by_id' => null,],
            ['id' => 115, 'shortcode' => 'JE', 'title' => 'Jersey', 'created_by_id' => null,],
            ['id' => 116, 'shortcode' => 'JT', 'title' => 'Johnston Island', 'created_by_id' => null,],
            ['id' => 117, 'shortcode' => 'JO', 'title' => 'Jordan', 'created_by_id' => null,],
            ['id' => 118, 'shortcode' => 'KZ', 'title' => 'Kazakhstan', 'created_by_id' => null,],
            ['id' => 119, 'shortcode' => 'KE', 'title' => 'Kenya', 'created_by_id' => null,],
            ['id' => 120, 'shortcode' => 'KI', 'title' => 'Kiribati', 'created_by_id' => null,],
            ['id' => 121, 'shortcode' => 'KW', 'title' => 'Kuwait', 'created_by_id' => null,],
            ['id' => 122, 'shortcode' => 'KG', 'title' => 'Kyrgyzstan', 'created_by_id' => null,],
            ['id' => 123, 'shortcode' => 'LA', 'title' => 'Laos', 'created_by_id' => null,],
            ['id' => 124, 'shortcode' => 'LV', 'title' => 'Latvia', 'created_by_id' => null,],
            ['id' => 125, 'shortcode' => 'LB', 'title' => 'Lebanon', 'created_by_id' => null,],
            ['id' => 126, 'shortcode' => 'LS', 'title' => 'Lesotho', 'created_by_id' => null,],
            ['id' => 127, 'shortcode' => 'LR', 'title' => 'Liberia', 'created_by_id' => null,],
            ['id' => 128, 'shortcode' => 'LY', 'title' => 'Libya', 'created_by_id' => null,],
            ['id' => 129, 'shortcode' => 'LI', 'title' => 'Liechtenstein', 'created_by_id' => null,],
            ['id' => 130, 'shortcode' => 'LT', 'title' => 'Lithuania', 'created_by_id' => null,],
            ['id' => 131, 'shortcode' => 'LU', 'title' => 'Luxembourg', 'created_by_id' => null,],
            ['id' => 132, 'shortcode' => 'MO', 'title' => 'Macau SAR China', 'created_by_id' => null,],
            ['id' => 133, 'shortcode' => 'MK', 'title' => 'Macedonia', 'created_by_id' => null,],
            ['id' => 134, 'shortcode' => 'MG', 'title' => 'Madagascar', 'created_by_id' => null,],
            ['id' => 135, 'shortcode' => 'MW', 'title' => 'Malawi', 'created_by_id' => null,],
            ['id' => 136, 'shortcode' => 'MY', 'title' => 'Malaysia', 'created_by_id' => null,],
            ['id' => 137, 'shortcode' => 'MV', 'title' => 'Maldives', 'created_by_id' => null,],
            ['id' => 138, 'shortcode' => 'ML', 'title' => 'Mali', 'created_by_id' => null,],
            ['id' => 139, 'shortcode' => 'MT', 'title' => 'Malta', 'created_by_id' => null,],
            ['id' => 140, 'shortcode' => 'MH', 'title' => 'Marshall Islands', 'created_by_id' => null,],
            ['id' => 141, 'shortcode' => 'MQ', 'title' => 'Martinique', 'created_by_id' => null,],
            ['id' => 142, 'shortcode' => 'MR', 'title' => 'Mauritania', 'created_by_id' => null,],
            ['id' => 143, 'shortcode' => 'MU', 'title' => 'Mauritius', 'created_by_id' => null,],
            ['id' => 144, 'shortcode' => 'YT', 'title' => 'Mayotte', 'created_by_id' => null,],
            ['id' => 145, 'shortcode' => 'FX', 'title' => 'Metropolitan France', 'created_by_id' => null,],
            ['id' => 146, 'shortcode' => 'MX', 'title' => 'Mexico', 'created_by_id' => null,],
            ['id' => 147, 'shortcode' => 'FM', 'title' => 'Micronesia', 'created_by_id' => null,],
            ['id' => 148, 'shortcode' => 'MI', 'title' => 'Midway Islands', 'created_by_id' => null,],
            ['id' => 149, 'shortcode' => 'MD', 'title' => 'Moldova', 'created_by_id' => null,],
            ['id' => 150, 'shortcode' => 'MC', 'title' => 'Monaco', 'created_by_id' => null,],
            ['id' => 151, 'shortcode' => 'MN', 'title' => 'Mongolia', 'created_by_id' => null,],
            ['id' => 152, 'shortcode' => 'ME', 'title' => 'Montenegro', 'created_by_id' => null,],
            ['id' => 153, 'shortcode' => 'MS', 'title' => 'Montserrat', 'created_by_id' => null,],
            ['id' => 154, 'shortcode' => 'MA', 'title' => 'Morocco', 'created_by_id' => null,],
            ['id' => 155, 'shortcode' => 'MZ', 'title' => 'Mozambique', 'created_by_id' => null,],
            ['id' => 156, 'shortcode' => 'MM', 'title' => 'Myanmar [Burma]', 'created_by_id' => null,],
            ['id' => 157, 'shortcode' => 'NA', 'title' => 'Namibia', 'created_by_id' => null,],
            ['id' => 158, 'shortcode' => 'NR', 'title' => 'Nauru', 'created_by_id' => null,],
            ['id' => 159, 'shortcode' => 'NP', 'title' => 'Nepal', 'created_by_id' => null,],
            ['id' => 160, 'shortcode' => 'NL', 'title' => 'Netherlands', 'created_by_id' => null,],
            ['id' => 161, 'shortcode' => 'AN', 'title' => 'Netherlands Antilles', 'created_by_id' => null,],
            ['id' => 162, 'shortcode' => 'NT', 'title' => 'Neutral Zone', 'created_by_id' => null,],
            ['id' => 163, 'shortcode' => 'NC', 'title' => 'New Caledonia', 'created_by_id' => null,],
            ['id' => 164, 'shortcode' => 'NZ', 'title' => 'New Zealand', 'created_by_id' => null,],
            ['id' => 165, 'shortcode' => 'NI', 'title' => 'Nicaragua', 'created_by_id' => null,],
            ['id' => 166, 'shortcode' => 'NE', 'title' => 'Niger', 'created_by_id' => null,],
            ['id' => 167, 'shortcode' => 'NG', 'title' => 'Nigeria', 'created_by_id' => null,],
            ['id' => 168, 'shortcode' => 'NU', 'title' => 'Niue', 'created_by_id' => null,],
            ['id' => 169, 'shortcode' => 'NF', 'title' => 'Norfolk Island', 'created_by_id' => null,],
            ['id' => 170, 'shortcode' => 'KP', 'title' => 'North Korea', 'created_by_id' => null,],
            ['id' => 171, 'shortcode' => 'VD', 'title' => 'North Vietnam', 'created_by_id' => null,],
            ['id' => 172, 'shortcode' => 'MP', 'title' => 'Northern Mariana Islands', 'created_by_id' => null,],
            ['id' => 173, 'shortcode' => 'NO', 'title' => 'Norway', 'created_by_id' => null,],
            ['id' => 174, 'shortcode' => 'OM', 'title' => 'Oman', 'created_by_id' => null,],
            ['id' => 175, 'shortcode' => 'PC', 'title' => 'Pacific Islands Trust Territory', 'created_by_id' => null,],
            ['id' => 176, 'shortcode' => 'PK', 'title' => 'Pakistan', 'created_by_id' => null,],
            ['id' => 177, 'shortcode' => 'PW', 'title' => 'Palau', 'created_by_id' => null,],
            ['id' => 178, 'shortcode' => 'PS', 'title' => 'Palestinian Territories', 'created_by_id' => null,],
            ['id' => 179, 'shortcode' => 'PA', 'title' => 'Panama', 'created_by_id' => null,],
            ['id' => 180, 'shortcode' => 'PZ', 'title' => 'Panama Canal Zone', 'created_by_id' => null,],
            ['id' => 181, 'shortcode' => 'PG', 'title' => 'Papua New Guinea', 'created_by_id' => null,],
            ['id' => 182, 'shortcode' => 'PY', 'title' => 'Paraguay', 'created_by_id' => null,],
            ['id' => 183, 'shortcode' => 'YD', 'title' => 'People\'s Democratic Republic of Yemen', 'created_by_id' => null,],
            ['id' => 184, 'shortcode' => 'PE', 'title' => 'Peru', 'created_by_id' => null,],
            ['id' => 185, 'shortcode' => 'PH', 'title' => 'Philippines', 'created_by_id' => null,],
            ['id' => 186, 'shortcode' => 'PN', 'title' => 'Pitcairn Islands', 'created_by_id' => null,],
            ['id' => 187, 'shortcode' => 'PL', 'title' => 'Poland', 'created_by_id' => null,],
            ['id' => 188, 'shortcode' => 'PT', 'title' => 'Portugal', 'created_by_id' => null,],
            ['id' => 189, 'shortcode' => 'PR', 'title' => 'Puerto Rico', 'created_by_id' => null,],
            ['id' => 190, 'shortcode' => 'QA', 'title' => 'Qatar', 'created_by_id' => null,],
            ['id' => 191, 'shortcode' => 'RO', 'title' => 'Romania', 'created_by_id' => null,],
            ['id' => 192, 'shortcode' => 'RU', 'title' => 'Russia', 'created_by_id' => null,],
            ['id' => 193, 'shortcode' => 'RW', 'title' => 'Rwanda', 'created_by_id' => null,],
            ['id' => 194, 'shortcode' => 'RE', 'title' => 'Réunion', 'created_by_id' => null,],
            ['id' => 195, 'shortcode' => 'BL', 'title' => 'Saint Barthélemy', 'created_by_id' => null,],
            ['id' => 196, 'shortcode' => 'SH', 'title' => 'Saint Helena', 'created_by_id' => null,],
            ['id' => 197, 'shortcode' => 'KN', 'title' => 'Saint Kitts and Nevis', 'created_by_id' => null,],
            ['id' => 198, 'shortcode' => 'LC', 'title' => 'Saint Lucia', 'created_by_id' => null,],
            ['id' => 199, 'shortcode' => 'MF', 'title' => 'Saint Martin', 'created_by_id' => null,],
            ['id' => 200, 'shortcode' => 'PM', 'title' => 'Saint Pierre and Miquelon', 'created_by_id' => null,],
            ['id' => 201, 'shortcode' => 'VC', 'title' => 'Saint Vincent and the Grenadines', 'created_by_id' => null,],
            ['id' => 202, 'shortcode' => 'WS', 'title' => 'Samoa', 'created_by_id' => null,],
            ['id' => 203, 'shortcode' => 'SM', 'title' => 'San Marino', 'created_by_id' => null,],
            ['id' => 204, 'shortcode' => 'SA', 'title' => 'Saudi Arabia', 'created_by_id' => null,],
            ['id' => 205, 'shortcode' => 'SN', 'title' => 'Senegal', 'created_by_id' => null,],
            ['id' => 206, 'shortcode' => 'RS', 'title' => 'Serbia', 'created_by_id' => null,],
            ['id' => 207, 'shortcode' => 'CS', 'title' => 'Serbia and Montenegro', 'created_by_id' => null,],
            ['id' => 208, 'shortcode' => 'SC', 'title' => 'Seychelles', 'created_by_id' => null,],
            ['id' => 209, 'shortcode' => 'SL', 'title' => 'Sierra Leone', 'created_by_id' => null,],
            ['id' => 210, 'shortcode' => 'SG', 'title' => 'Singapore', 'created_by_id' => null,],
            ['id' => 211, 'shortcode' => 'SK', 'title' => 'Slovakia', 'created_by_id' => null,],
            ['id' => 212, 'shortcode' => 'SI', 'title' => 'Slovenia', 'created_by_id' => null,],
            ['id' => 213, 'shortcode' => 'SB', 'title' => 'Solomon Islands', 'created_by_id' => null,],
            ['id' => 214, 'shortcode' => 'SO', 'title' => 'Somalia', 'created_by_id' => null,],
            ['id' => 215, 'shortcode' => 'ZA', 'title' => 'South Africa', 'created_by_id' => null,],
            ['id' => 216, 'shortcode' => 'GS', 'title' => 'South Georgia and the South Sandwich Islands', 'created_by_id' => null,],
            ['id' => 217, 'shortcode' => 'KR', 'title' => 'South Korea', 'created_by_id' => null,],
            ['id' => 218, 'shortcode' => 'ES', 'title' => 'Spain', 'created_by_id' => null,],
            ['id' => 219, 'shortcode' => 'LK', 'title' => 'Sri Lanka', 'created_by_id' => null,],
            ['id' => 220, 'shortcode' => 'SD', 'title' => 'Sudan', 'created_by_id' => null,],
            ['id' => 221, 'shortcode' => 'SR', 'title' => 'Suriname', 'created_by_id' => null,],
            ['id' => 222, 'shortcode' => 'SJ', 'title' => 'Svalbard and Jan Mayen', 'created_by_id' => null,],
            ['id' => 223, 'shortcode' => 'SZ', 'title' => 'Swaziland', 'created_by_id' => null,],
            ['id' => 224, 'shortcode' => 'SE', 'title' => 'Sweden', 'created_by_id' => null,],
            ['id' => 225, 'shortcode' => 'CH', 'title' => 'Switzerland', 'created_by_id' => null,],
            ['id' => 226, 'shortcode' => 'SY', 'title' => 'Syria', 'created_by_id' => null,],
            ['id' => 227, 'shortcode' => 'ST', 'title' => 'São Tomé and Príncipe', 'created_by_id' => null,],
            ['id' => 228, 'shortcode' => 'TW', 'title' => 'Taiwan', 'created_by_id' => null,],
            ['id' => 229, 'shortcode' => 'TJ', 'title' => 'Tajikistan', 'created_by_id' => null,],
            ['id' => 230, 'shortcode' => 'TZ', 'title' => 'Tanzania', 'created_by_id' => null,],
            ['id' => 231, 'shortcode' => 'TH', 'title' => 'Thailand', 'created_by_id' => null,],
            ['id' => 232, 'shortcode' => 'TL', 'title' => 'Timor-Leste', 'created_by_id' => null,],
            ['id' => 233, 'shortcode' => 'TG', 'title' => 'Togo', 'created_by_id' => null,],
            ['id' => 234, 'shortcode' => 'TK', 'title' => 'Tokelau', 'created_by_id' => null,],
            ['id' => 235, 'shortcode' => 'TO', 'title' => 'Tonga', 'created_by_id' => null,],
            ['id' => 236, 'shortcode' => 'TT', 'title' => 'Trinidad and Tobago', 'created_by_id' => null,],
            ['id' => 237, 'shortcode' => 'TN', 'title' => 'Tunisia', 'created_by_id' => null,],
            ['id' => 238, 'shortcode' => 'TR', 'title' => 'Turkey', 'created_by_id' => null,],
            ['id' => 239, 'shortcode' => 'TM', 'title' => 'Turkmenistan', 'created_by_id' => null,],
            ['id' => 240, 'shortcode' => 'TC', 'title' => 'Turks and Caicos Islands', 'created_by_id' => null,],
            ['id' => 241, 'shortcode' => 'TV', 'title' => 'Tuvalu', 'created_by_id' => null,],
            ['id' => 242, 'shortcode' => 'UM', 'title' => 'U.S. Minor Outlying Islands', 'created_by_id' => null,],
            ['id' => 243, 'shortcode' => 'PU', 'title' => 'U.S. Miscellaneous Pacific Islands', 'created_by_id' => null,],
            ['id' => 244, 'shortcode' => 'VI', 'title' => 'U.S. Virgin Islands', 'created_by_id' => null,],
            ['id' => 245, 'shortcode' => 'UG', 'title' => 'Uganda', 'created_by_id' => null,],
            ['id' => 246, 'shortcode' => 'UA', 'title' => 'Ukraine', 'created_by_id' => null,],
            ['id' => 247, 'shortcode' => 'SU', 'title' => 'Union of Soviet Socialist Republics', 'created_by_id' => null,],
            ['id' => 248, 'shortcode' => 'AE', 'title' => 'United Arab Emirates', 'created_by_id' => null,],
            ['id' => 249, 'shortcode' => 'GB', 'title' => 'United Kingdom', 'created_by_id' => null,],
            ['id' => 250, 'shortcode' => 'US', 'title' => 'United States', 'created_by_id' => null,],
            ['id' => 251, 'shortcode' => 'ZZ', 'title' => 'Unknown or Invalid Region', 'created_by_id' => null,],
            ['id' => 252, 'shortcode' => 'UY', 'title' => 'Uruguay', 'created_by_id' => null,],
            ['id' => 253, 'shortcode' => 'UZ', 'title' => 'Uzbekistan', 'created_by_id' => null,],
            ['id' => 254, 'shortcode' => 'VU', 'title' => 'Vanuatu', 'created_by_id' => null,],
            ['id' => 255, 'shortcode' => 'VA', 'title' => 'Vatican City', 'created_by_id' => null,],
            ['id' => 256, 'shortcode' => 'VE', 'title' => 'Venezuela', 'created_by_id' => null,],
            ['id' => 257, 'shortcode' => 'VN', 'title' => 'Vietnam', 'created_by_id' => null,],
            ['id' => 258, 'shortcode' => 'WK', 'title' => 'Wake Island', 'created_by_id' => null,],
            ['id' => 259, 'shortcode' => 'WF', 'title' => 'Wallis and Futuna', 'created_by_id' => null,],
            ['id' => 260, 'shortcode' => 'EH', 'title' => 'Western Sahara', 'created_by_id' => null,],
            ['id' => 261, 'shortcode' => 'YE', 'title' => 'Yemen', 'created_by_id' => null,],
            ['id' => 262, 'shortcode' => 'ZM', 'title' => 'Zambia', 'created_by_id' => null,],
            ['id' => 263, 'shortcode' => 'ZW', 'title' => 'Zimbabwe', 'created_by_id' => null,],
            ['id' => 264, 'shortcode' => 'AX', 'title' => 'Åland Islands', 'created_by_id' => null,],

        ];

        foreach ($items as $item) {
            \App\Country::create($item);
        }
    }
}
