<?php

use Illuminate\Database\Seeder;

class PermissionSeed extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $items = [
            
            ['id' => 1, 'title' => 'user_management_access',],
            ['id' => 2, 'title' => 'user_management_create',],
            ['id' => 3, 'title' => 'user_management_edit',],
            ['id' => 4, 'title' => 'user_management_view',],
            ['id' => 5, 'title' => 'user_management_delete',],
            ['id' => 6, 'title' => 'permission_access',],
            ['id' => 7, 'title' => 'permission_create',],
            ['id' => 8, 'title' => 'permission_edit',],
            ['id' => 9, 'title' => 'permission_view',],
            ['id' => 10, 'title' => 'permission_delete',],
            ['id' => 11, 'title' => 'role_access',],
            ['id' => 12, 'title' => 'role_create',],
            ['id' => 13, 'title' => 'role_edit',],
            ['id' => 14, 'title' => 'role_view',],
            ['id' => 15, 'title' => 'role_delete',],
            ['id' => 16, 'title' => 'user_access',],
            ['id' => 17, 'title' => 'user_create',],
            ['id' => 18, 'title' => 'user_edit',],
            ['id' => 19, 'title' => 'user_view',],
            ['id' => 20, 'title' => 'user_delete',],
            ['id' => 21, 'title' => 'user_action_access',],
            ['id' => 22, 'title' => 'user_action_create',],
            ['id' => 23, 'title' => 'user_action_edit',],
            ['id' => 24, 'title' => 'user_action_view',],
            ['id' => 25, 'title' => 'user_action_delete',],
            ['id' => 26, 'title' => 'faq_management_access',],
            ['id' => 27, 'title' => 'faq_management_create',],
            ['id' => 28, 'title' => 'faq_management_edit',],
            ['id' => 29, 'title' => 'faq_management_view',],
            ['id' => 30, 'title' => 'faq_management_delete',],
            ['id' => 31, 'title' => 'faq_category_access',],
            ['id' => 32, 'title' => 'faq_category_create',],
            ['id' => 33, 'title' => 'faq_category_edit',],
            ['id' => 34, 'title' => 'faq_category_view',],
            ['id' => 35, 'title' => 'faq_category_delete',],
            ['id' => 36, 'title' => 'faq_question_access',],
            ['id' => 37, 'title' => 'faq_question_create',],
            ['id' => 38, 'title' => 'faq_question_edit',],
            ['id' => 39, 'title' => 'faq_question_view',],
            ['id' => 40, 'title' => 'faq_question_delete',],
            ['id' => 41, 'title' => 'internal_notification_access',],
            ['id' => 42, 'title' => 'internal_notification_create',],
            ['id' => 43, 'title' => 'internal_notification_edit',],
            ['id' => 44, 'title' => 'internal_notification_view',],
            ['id' => 45, 'title' => 'internal_notification_delete',],
            ['id' => 46, 'title' => 'content_management_access',],
            ['id' => 47, 'title' => 'content_management_create',],
            ['id' => 48, 'title' => 'content_management_edit',],
            ['id' => 49, 'title' => 'content_management_view',],
            ['id' => 50, 'title' => 'content_management_delete',],
            ['id' => 51, 'title' => 'content_category_access',],
            ['id' => 52, 'title' => 'content_category_create',],
            ['id' => 53, 'title' => 'content_category_edit',],
            ['id' => 54, 'title' => 'content_category_view',],
            ['id' => 55, 'title' => 'content_category_delete',],
            ['id' => 56, 'title' => 'content_tag_access',],
            ['id' => 57, 'title' => 'content_tag_create',],
            ['id' => 58, 'title' => 'content_tag_edit',],
            ['id' => 59, 'title' => 'content_tag_view',],
            ['id' => 60, 'title' => 'content_tag_delete',],
            ['id' => 61, 'title' => 'content_page_access',],
            ['id' => 62, 'title' => 'content_page_create',],
            ['id' => 63, 'title' => 'content_page_edit',],
            ['id' => 64, 'title' => 'content_page_view',],
            ['id' => 65, 'title' => 'content_page_delete',],
            ['id' => 66, 'title' => 'setting_access',],
            ['id' => 67, 'title' => 'site_setting_access',],
            ['id' => 68, 'title' => 'site_setting_create',],
            ['id' => 69, 'title' => 'site_setting_edit',],
            ['id' => 70, 'title' => 'site_setting_view',],
            ['id' => 71, 'title' => 'site_setting_delete',],
            ['id' => 72, 'title' => 'auction_setting_access',],
            ['id' => 73, 'title' => 'auction_setting_create',],
            ['id' => 74, 'title' => 'auction_setting_edit',],
            ['id' => 75, 'title' => 'auction_setting_view',],
            ['id' => 76, 'title' => 'auction_setting_delete',],
            ['id' => 77, 'title' => 'currency_setting_access',],
            ['id' => 78, 'title' => 'currency_setting_create',],
            ['id' => 79, 'title' => 'currency_setting_edit',],
            ['id' => 80, 'title' => 'currency_setting_view',],
            ['id' => 81, 'title' => 'currency_setting_delete',],
            ['id' => 82, 'title' => 'time_setting_access',],
            ['id' => 83, 'title' => 'time_setting_create',],
            ['id' => 84, 'title' => 'time_setting_edit',],
            ['id' => 85, 'title' => 'time_setting_view',],
            ['id' => 86, 'title' => 'time_setting_delete',],
            ['id' => 87, 'title' => 'seo_setting_access',],
            ['id' => 88, 'title' => 'seo_setting_create',],
            ['id' => 89, 'title' => 'seo_setting_edit',],
            ['id' => 90, 'title' => 'seo_setting_view',],
            ['id' => 91, 'title' => 'seo_setting_delete',],
            ['id' => 93, 'title' => 'payment_gateway_access',],
            ['id' => 94, 'title' => 'paypal_access',],
            ['id' => 95, 'title' => 'paypal_create',],
            ['id' => 96, 'title' => 'paypal_edit',],
            ['id' => 97, 'title' => 'paypal_view',],
            ['id' => 98, 'title' => 'paypal_delete',],
            ['id' => 99, 'title' => 'category_access',],
            ['id' => 100, 'title' => 'category_create',],
            ['id' => 101, 'title' => 'category_edit',],
            ['id' => 102, 'title' => 'category_view',],
            ['id' => 103, 'title' => 'category_delete',],
            ['id' => 104, 'title' => 'sub_catogory_access',],
            ['id' => 105, 'title' => 'sub_catogory_create',],
            ['id' => 106, 'title' => 'sub_catogory_edit',],
            ['id' => 107, 'title' => 'sub_catogory_view',],
            ['id' => 108, 'title' => 'sub_catogory_delete',],
            ['id' => 109, 'title' => 'auction_access',],
            ['id' => 110, 'title' => 'create_access',],
            ['id' => 111, 'title' => 'create_create',],
            ['id' => 112, 'title' => 'create_edit',],
            ['id' => 113, 'title' => 'create_view',],
            ['id' => 114, 'title' => 'create_delete',],
            ['id' => 115, 'title' => 'testmony_access',],
            ['id' => 116, 'title' => 'testmony_create',],
            ['id' => 117, 'title' => 'testmony_edit',],
            ['id' => 118, 'title' => 'testmony_view',],
            ['id' => 119, 'title' => 'testmony_delete',],
            ['id' => 120, 'title' => 'social_login_access',],
            ['id' => 121, 'title' => 'social_login_create',],
            ['id' => 122, 'title' => 'social_login_edit',],
            ['id' => 123, 'title' => 'social_login_view',],
            ['id' => 124, 'title' => 'social_login_delete',],
            ['id' => 125, 'title' => 'email_setting_access',],
            ['id' => 126, 'title' => 'template_access',],
            ['id' => 127, 'title' => 'template_create',],
            ['id' => 128, 'title' => 'template_edit',],
            ['id' => 129, 'title' => 'template_view',],
            ['id' => 130, 'title' => 'template_delete',],
            ['id' => 131, 'title' => 'news_letter_access',],
            ['id' => 132, 'title' => 'create_letter_access',],
            ['id' => 133, 'title' => 'create_letter_create',],
            ['id' => 134, 'title' => 'create_letter_edit',],
            ['id' => 135, 'title' => 'create_letter_view',],
            ['id' => 136, 'title' => 'create_letter_delete',],
            ['id' => 137, 'title' => 'social_network_access',],
            ['id' => 138, 'title' => 'location_master_access',],
            ['id' => 139, 'title' => 'country_access',],
            ['id' => 140, 'title' => 'country_create',],
            ['id' => 141, 'title' => 'country_edit',],
            ['id' => 142, 'title' => 'country_view',],
            ['id' => 143, 'title' => 'country_delete',],
            ['id' => 144, 'title' => 'state_access',],
            ['id' => 145, 'title' => 'state_create',],
            ['id' => 146, 'title' => 'state_edit',],
            ['id' => 147, 'title' => 'state_view',],
            ['id' => 148, 'title' => 'state_delete',],
            ['id' => 149, 'title' => 'city_access',],
            ['id' => 150, 'title' => 'city_create',],
            ['id' => 151, 'title' => 'city_edit',],
            ['id' => 152, 'title' => 'city_view',],
            ['id' => 153, 'title' => 'city_delete',],

        ];

        foreach ($items as $item) {
            \App\Permission::create($item);
        }
    }
}
